{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "\r\n<div style=\"display: flex; justify-content: center; align-items: center; height: 100%\">\r\n<h1 style=\"font-size: 100px; text-align: center\">FEIJÃO 4.0<h1>\r\n</div>"
   }
  },
  {
   "title": "Lista do feijão",
   "type": "table",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "feijao_db",
     "rawSql": "SELECT nome as NOME, baiana as \"TIPO DA FEIJOADA\" FROM feijao_db.lista"
    }
   ]
  },
  {
   "title": "Quantidade Baianas",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "feijao_db",
     "rawSql": "SELECT meias, inteiras FROM feijao_db.quantidades WHERE tipo = 'baiana' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Quantidade Cariocas",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "feijao_db",
     "rawSql": "SELECT meias, inteiras FROM feijao_db.quantidades WHERE tipo = 'carioca' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Relação - Feijoadas",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "feijao_db",
     "rawSql": "SELECT COUNT(baiana) as CARIOCA FROM feijao_db.lista WHERE baiana = '0'"
    },
    {
     "dataset": "feijao_db",
     "rawSql": "SELECT COUNT(baiana) as BAIANA FROM feijao_db.lista WHERE baiana = '1'"
    }
   ]
  }
 ]
}